### ISSUE TITLE
bench command not working

### ISSUE THREAD

**Issue by peak-load** [cloudflare/odoh-client-go#9]
Looks bench command is defunct:

- missing file with list of 10 hostnames (dataset.csv) defined here https://github.com/cloudflare/odoh-client-go/blob/0c01202fd15fa1cd4dc267aa5a5cf2ab092820e3/commands/commands.go#L93
- benchmark tries to send results in telemetry.go to Google Cloud here https://github.com/cloudflare/odoh-client-go/blob/0c01202fd15fa1cd4dc267aa5a5cf2ab092820e3/commands/telemetry.go#L44

Please make bench command working locally with optional usage of Elasticsearch or Google Cloud for submitting results.

**Comment by chris-wood** [comment]
Indeed -- thanks, @peak-load! That telemetry code is left over from [our analysis](https://arxiv.org/abs/2011.10121). We'll get it cleaned up soon.

**Comment by chris-wood** [comment]
Closing, as this should be fixed now. Please reopen if that's not the case!
